-- MySQL Script generated by MySQL Workbench
-- Thu Jul 26 11:41:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_MULTIMETER_SENA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_MULTIMETER_SENA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_MULTIMETER_SENA` DEFAULT CHARACTER SET utf8 ;
USE `DB_MULTIMETER_SENA` ;

-- -----------------------------------------------------
-- Table `DB_MULTIMETER_SENA`.`maker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_MULTIMETER_SENA`.`maker` (
  `MAKER_ID` INT NOT NULL,
  `MAKER_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MAKER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_MULTIMETER_SENA`.`reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_MULTIMETER_SENA`.`reference` (
  `REFERENCE_ID` INT NOT NULL,
  `REFERENCE_NAME` VARCHAR(45) NULL,
  `REFERENCE_IMG` VARCHAR(45) NULL,
  `REFERENCE_FILE` VARCHAR(500) NULL,
  `maker_MAKER_ID` INT NOT NULL,
  PRIMARY KEY (`REFERENCE_ID`),
  INDEX `fk_reference_maker_idx` (`maker_MAKER_ID` ASC),
  CONSTRAINT `fk_reference_maker`
    FOREIGN KEY (`maker_MAKER_ID`)
    REFERENCES `DB_MULTIMETER_SENA`.`maker` (`MAKER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_MULTIMETER_SENA`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_MULTIMETER_SENA`.`function` (
  `FUNCTION_ID` INT NOT NULL,
  `FUNCTION_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`FUNCTION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_MULTIMETER_SENA`.`function_has_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_MULTIMETER_SENA`.`function_has_reference` (
  `function_FUNCTION_ID` INT NOT NULL,
  `reference_REFERENCE_ID` INT NOT NULL,
  PRIMARY KEY (`function_FUNCTION_ID`, `reference_REFERENCE_ID`),
  INDEX `fk_function_has_reference_reference1_idx` (`reference_REFERENCE_ID` ASC),
  INDEX `fk_function_has_reference_function1_idx` (`function_FUNCTION_ID` ASC),
  CONSTRAINT `fk_function_has_reference_function1`
    FOREIGN KEY (`function_FUNCTION_ID`)
    REFERENCES `DB_MULTIMETER_SENA`.`function` (`FUNCTION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_function_has_reference_reference1`
    FOREIGN KEY (`reference_REFERENCE_ID`)
    REFERENCES `DB_MULTIMETER_SENA`.`reference` (`REFERENCE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
